debug: false
teamNames:
- Red
- Blue
- Orange
pvpRegionName: pvp
pvpCooldown: 30
playerPortalTpFailLocation: world,-10,75,10,0,0
Red:
  score: 0
  color: RED
  friendlyFire: false
  regionName: red
  players: []
  joinLocation: world,-10,75,0,0,90
  spawnLocation: world,-10,75,0,0,90
  portalLocation: []
Blue:
  score: 0
  color: BLUE
  friendlyFire: false
  regionName: blue
  players: []
  joinLocation: world,10,75,0,0,90
  spawnLocation: world,10,75,0,0,90
  portalLocation: []
Orange:
  score: 0
  color: ORANGE
  friendlyFire: true
  regionName: orange
  players: []
  joinLocation: world,0,75,10,0,90
  spawnLocation: world,0,75,10,0,90
  portalLocation: []
