teamNames: Red, Blue, Orange
friendlyFireDisabledRegions: pvp
Red:
  score: 0
  color: RED
  friendlyFire: false
  bedRegion: red
  players: []
  joinLocation: world,-10,75,0
  portalLocation: world,-10,75,0
Blue:
  score: 0
  color: BLUE
  friendlyFire: false
  bedRegion: blue
  players: []
  joinLocation: world,10,75,0
  portalLocation: world,10,75,0
Orange:
  score: 0
  color: ORANGE
  friendlyFire: true
  bedRegion: orange
  players: []
  joinLocation: world,0,75,10
  portalLocation: world,0,75,10
freeJoinUsed: []